#!/usr/bin/env bash
# PostToolUse hook: validate WCA post frontmatter after Edit/Write.
# Runs against files under content/posts/ only. Exits 2 (with stderr) when
# the file violates the project's post conventions so Claude sees the message
# and can fix it. See CLAUDE.md for the rules.

set -euo pipefail

input=$(cat)

file_path=$(printf '%s' "$input" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    print('')
    sys.exit(0)
print(d.get('tool_input', {}).get('file_path', '') or '')
")

# Only validate post markdown files
case "$file_path" in
  */content/posts/*.md) ;;
  *) exit 0 ;;
esac

# Auto-generated by PostList.vue — never edit
if [[ "$file_path" == */content/posts/index.md ]]; then
  echo "ERROR: $file_path is auto-generated by PostList.vue — do not edit it directly." >&2
  exit 2
fi

# Section config — fine to edit
if [[ "$file_path" == */content/posts/_dir.yml ]]; then
  exit 0
fi

# Extract frontmatter (between the first two --- markers)
if [[ ! -f "$file_path" ]]; then
  exit 0
fi

frontmatter=$(awk '
  /^---[[:space:]]*$/ { c++; next }
  c==1 { print }
  c==2 { exit }
' "$file_path")

if [[ -z "$frontmatter" ]]; then
  echo "ERROR: $file_path has no YAML frontmatter block. Expected '---' delimiters with navigation.title, layout, title, description." >&2
  exit 2
fi

errors=()

for key in 'navigation\.title' 'layout' 'title' 'description'; do
  if ! printf '%s\n' "$frontmatter" | grep -qE "^[[:space:]]*${key}[[:space:]]*:"; then
    # Pretty-print the key in the error message
    pretty=${key//\\./.}
    errors+=("missing required frontmatter key: ${pretty}")
  fi
done

if printf '%s\n' "$frontmatter" | grep -qE "^[[:space:]]*navigation\.path[[:space:]]*:"; then
  errors+=("navigation.path must not be set — Nuxt generates the URL from the filename (see CLAUDE.md)")
fi

if (( ${#errors[@]} > 0 )); then
  echo "ERROR: $file_path frontmatter is invalid:" >&2
  for e in "${errors[@]}"; do
    echo "  - $e" >&2
  done
  exit 2
fi

exit 0
