name: Create Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Release Version
        id: version
        run: |
          # Generate version based on date and commit hash
          DATE=$(date +'%Y.%m.%d')
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          VERSION="v${DATE}-${SHORT_SHA}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Generated version: ${VERSION}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/neighborhood-covenant.pdf
          asset_name: Woodmont-Neighborhood-Covenant.pdf
          asset_content_type: application/pdf
